alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress: {}
name: slippilab-uploader-bot
envs:
  - key: DISCORD_TOKEN
    value: ${DISCORD_TOKEN}
    type: SECRET
region: lon
workers:
- dockerfile_path: /Dockerfile
  github:
    branch: main
    deploy_on_push: false
    repo: manniefesto/slippilab-uploader-discord-bot
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: slippilab-uploader-discord-bot
  source_dir: /