name: Deploy
on:
  release:
    types: [published]

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}